dist: bionic
language: python
install:
  - pip install ansible ansible-lint
  - ansible-lint --version
  - ansible-galaxy install avinetworks.docker
  - ansible-galaxy install atosatto.docker-swarm
  - sudo wget https://download.virtualbox.org/virtualbox/6.1.4/virtualbox-6.1_6.1.4-136177~Ubuntu~bionic_amd64.deb
  - sudo dpkg -i virtualbox-6.1_6.1.4-136177~Ubuntu~bionic_amd64.deb
  - VBoxManage --version
  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.19/vagrant_2.2.19_x86_64.deb
  - sudo dpkg -i vagrant_2.2.19_x86_64.deb
  - vagrant --version
  - pip install "molecule[lint]"
  - pip install molecule-vagrant
script:
  - ansible-lint --exclude ${HOME}/.ansible/roles/ --exclude ./roles playbook.yml
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
