language: python
install:
  - pip install ansible ansible-lint
  - ansible-lint --version
  - ansible-galaxy install avinetworks.docker
  - ansible-galaxy install atosatto.docker-swarm
  - sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.19/vagrant_2.2.19_x86_64.deb
  - sudo dpkg -i vagrant_2.2.7_x86_64.deb
  - vagrant --version
  - sudo vagrant plugin install vagrant-libvirt
  - pip install "molecule[lint]"
  - pip install molecule-vagrant
script:
  - ansible-lint --exclude ${HOME}/.ansible/roles/ --exclude ./roles playbook.yml
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
