---
- hosts: all
  become: true
  roles:
    - role: "avinetworks.docker"


- name: Enable ports to expose docker daemon REST API
  hosts: all
  become: true
  vars:
    certdir: "~/my_certificate_directory"
  tasks:
    - name: Enable port 2376
      firewalld:
        zone: public
        port: "2376/tcp"
        permanent: true
        state: enabled
      notify: Reload firewalld
  handlers:
    - name: Reload firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded
- name: Secure the docker daemon on vm1
  hosts: vm1
  become: true
  roles:
    - role: role-secure-docker-daemon
      dds_host: 192.168.56.120
      dds_server_cert_path: /etc/default/docker
      dds_restart_docker: true
- name: Secure the docker daemon on vm2
  hosts: vm2
  become: true
  roles:
    - role: role-secure-docker-daemon
      dds_host: 192.168.56.121
      dds_server_cert_path: /etc/default/docker
      dds_restart_docker: true


- name: Enable ports for docker swarm
  hosts: all
  become: true
  tasks:
    - name: Enable port 2377, 7946, 4789 for docker swarm
      firewalld:
        zone: public
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - 2377/tcp
        - 7946/tcp
        - 7946/udp
        - 4789/udp
      notify: Reload firewalld
  handlers:
    - name: Reload firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded
- hosts: all
  become: true
  roles:
    - role: "atosatto.docker-swarm"
      docker_swarm_interface: "eth1"
