---
- hosts: all
  become: true
  roles:
    - role: "avinetworks.docker"

- hosts: all
  tasks:
    - name: "Enable 2375 port"
      firewalld:
        zone: public
        port: "2375/tcp"
        permanent: true
        state: enabled
      become: true
    - name: "Reload firewalld"
      command: firewall-cmd --reload
      become: true
    - name: "Replace line"
      lineinfile: 
        path: /lib/systemd/system/docker.service
        regexp: '^(.*)ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock(.*)$' 
        line: 'ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock  -H=tcp://0.0.0.0:2375'
        backrefs: true
    - name: "Reload deamon"
      command: "systemctl daemon-reload"
    - name: "Reload docker service"
      command: "sudo service docker restart"

- hosts: all
  become: true
  tasks:
    - name: ""
      firewalld:
        zone: public
        port: "{{ item }}"
        permanent: true
        state: enabled
      become: true
      with_items:
        - 2377/tcp
        - 7946/tcp
        - 7946/udp
        - 4789/udp
    - name: "Reload firewalld"
      command: firewall-cmd --reload
      become: true

- hosts: all
  become: true
  roles:
    - role: "atosatto.docker-swarm"
      docker_swarm_interface: "eth1"
